# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/sysgen/dsp_blr_clock.xdc

# XDC: imports/sysgen/dsp_blr.xdc

# Block Designs: bd/dsp_blr_bd/dsp_blr_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dsp_blr_bd || ORIG_REF_NAME==dsp_blr_bd} -quiet] -quiet

# IP: bd/dsp_blr_bd/ip/dsp_blr_bd_dsp_blr_1_0/dsp_blr_bd_dsp_blr_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dsp_blr_bd_dsp_blr_1_0 || ORIG_REF_NAME==dsp_blr_bd_dsp_blr_1_0} -quiet] -quiet

# XDC: bd/dsp_blr_bd/dsp_blr_bd_ooc.xdc
