# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/1905p/git_repos/KRD/SysGen_project/dsp_blr/ip_catalog/dsp_blr.srcs/sources_1/ip/dsp_blr_0/dsp_blr_0.xci
# IP: The module: 'dsp_blr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/1905p/git_repos/KRD/SysGen_project/dsp_blr/ip_catalog/dsp_blr.srcs/sources_1/ip/dsp_blr_0/dsp_blr_c_addsub_v12_0_i0/dsp_blr_c_addsub_v12_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dsp_blr_c_addsub_v12_0_i0 || ORIG_REF_NAME==dsp_blr_c_addsub_v12_0_i0} -quiet] -quiet

# IP: c:/Users/1905p/git_repos/KRD/SysGen_project/dsp_blr/ip_catalog/dsp_blr.srcs/sources_1/ip/dsp_blr_0/dsp_blr_c_addsub_v12_0_i1/dsp_blr_c_addsub_v12_0_i1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dsp_blr_c_addsub_v12_0_i1 || ORIG_REF_NAME==dsp_blr_c_addsub_v12_0_i1} -quiet] -quiet

# IP: c:/Users/1905p/git_repos/KRD/SysGen_project/dsp_blr/ip_catalog/dsp_blr.srcs/sources_1/ip/dsp_blr_0/dsp_blr_c_addsub_v12_0_i2/dsp_blr_c_addsub_v12_0_i2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dsp_blr_c_addsub_v12_0_i2 || ORIG_REF_NAME==dsp_blr_c_addsub_v12_0_i2} -quiet] -quiet

# IP: c:/Users/1905p/git_repos/KRD/SysGen_project/dsp_blr/ip_catalog/dsp_blr.srcs/sources_1/ip/dsp_blr_0/dsp_blr_c_addsub_v12_0_i3/dsp_blr_c_addsub_v12_0_i3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dsp_blr_c_addsub_v12_0_i3 || ORIG_REF_NAME==dsp_blr_c_addsub_v12_0_i3} -quiet] -quiet

# XDC: c:/Users/1905p/git_repos/KRD/SysGen_project/dsp_blr/ip_catalog/dsp_blr.srcs/sources_1/ip/dsp_blr_0/constrs/dsp_blr.xdc
# XDC: The top module name and the constraint reference have the same name: 'dsp_blr_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/1905p/git_repos/KRD/SysGen_project/dsp_blr/ip_catalog/dsp_blr.srcs/sources_1/ip/dsp_blr_0/dsp_blr_0.xci
# IP: The module: 'dsp_blr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/1905p/git_repos/KRD/SysGen_project/dsp_blr/ip_catalog/dsp_blr.srcs/sources_1/ip/dsp_blr_0/dsp_blr_c_addsub_v12_0_i0/dsp_blr_c_addsub_v12_0_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dsp_blr_c_addsub_v12_0_i0 || ORIG_REF_NAME==dsp_blr_c_addsub_v12_0_i0} -quiet] -quiet

# IP: c:/Users/1905p/git_repos/KRD/SysGen_project/dsp_blr/ip_catalog/dsp_blr.srcs/sources_1/ip/dsp_blr_0/dsp_blr_c_addsub_v12_0_i1/dsp_blr_c_addsub_v12_0_i1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dsp_blr_c_addsub_v12_0_i1 || ORIG_REF_NAME==dsp_blr_c_addsub_v12_0_i1} -quiet] -quiet

# IP: c:/Users/1905p/git_repos/KRD/SysGen_project/dsp_blr/ip_catalog/dsp_blr.srcs/sources_1/ip/dsp_blr_0/dsp_blr_c_addsub_v12_0_i2/dsp_blr_c_addsub_v12_0_i2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dsp_blr_c_addsub_v12_0_i2 || ORIG_REF_NAME==dsp_blr_c_addsub_v12_0_i2} -quiet] -quiet

# IP: c:/Users/1905p/git_repos/KRD/SysGen_project/dsp_blr/ip_catalog/dsp_blr.srcs/sources_1/ip/dsp_blr_0/dsp_blr_c_addsub_v12_0_i3/dsp_blr_c_addsub_v12_0_i3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dsp_blr_c_addsub_v12_0_i3 || ORIG_REF_NAME==dsp_blr_c_addsub_v12_0_i3} -quiet] -quiet

# XDC: c:/Users/1905p/git_repos/KRD/SysGen_project/dsp_blr/ip_catalog/dsp_blr.srcs/sources_1/ip/dsp_blr_0/constrs/dsp_blr.xdc
# XDC: The top module name and the constraint reference have the same name: 'dsp_blr_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
