set_property PACKAGE_PIN AL17 [get_ports CLK_IN1_D_0_clk_p]
set_property IOSTANDARD LVDS [get_ports CLK_IN1_D_0_clk_p]
set_property PACKAGE_PIN AP13 [get_ports DATAFRAME_GEN_ERROR_0]
set_property IOSTANDARD LVCMOS18 [get_ports DATAFRAME_GEN_ERROR_0]

set_property PACKAGE_PIN AR16 [get_ports CLK_LOCKED_LED]
set_property IOSTANDARD LVCMOS18 [get_ports CLK_LOCKED_LED]
set_property PACKAGE_PIN AF15 [get_ports EXT_RESET]
set_property PACKAGE_PIN AR13 [get_ports {RESET_LED[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RESET_LED[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports EXT_RESET]
