####################################################################################
# PL clock pins
####################################################################################
 set_property PACKAGE_PIN AU10 [get_ports {PL_SYSTEM_CLK_clk_p[0]}]
 set_property PACKAGE_PIN B22 [get_ports {PL_SYSREF_clk_p[0]}]

 set_property CLOCK_DEDICATED_ROUTE ANY_CMT_COLUMN [get_nets {mogura2_fee_i/mts_clk/pl_system_clk_bufg/U0/BUFG_O[0]}]


 set_property IOSTANDARD LVDS_25 [get_ports {PL_SYSTEM_CLK_clk_p[0]}]
 set_property IOSTANDARD DIFF_HSTL_I_12 [get_ports {PL_SYSREF_clk_p[0]}]
 create_clock -period 32.000 -name PL_SYSTEM_CLK_clk_p -waveform {0.000 16.000} [get_ports PL_SYSTEM_CLK_clk_p]

####################################################################################
# ADC/DAC clock options
####################################################################################

 create_clock -period 4.000 -name usp_rf_data_converter_0_adc0_clk [get_ports adc0_clk_clk_p]
 create_clock -period 4.000 -name usp_rf_data_converter_0_adc1_clk [get_ports adc1_clk_clk_p]
 create_clock -period 4.000 -name usp_rf_data_converter_0_adc2_clk [get_ports adc2_clk_clk_p]
 create_clock -period 4.000 -name usp_rf_data_converter_0_adc3_clk [get_ports adc3_clk_clk_p]
#create_clock -period 4.000 -name usp_rf_data_converter_0_dac0_clk [get_ports dac0_clk_clk_p]
#create_clock -period 4.000 -name usp_rf_data_converter_0_dac1_clk [get_ports dac1_clk_clk_p]
#create_clock -period 4.000 -name usp_rf_data_converter_0_dac2_clk [get_ports dac2_clk_clk_p]
#create_clock -period 4.000 -name usp_rf_data_converter_0_dac3_clk [get_ports dac3_clk_clk_p]

####################################################################################
# SPI pins
####################################################################################
 set_property PACKAGE_PIN C14 [get_ports SPI_LADC_0_sck_io]
 set_property PACKAGE_PIN B13 [get_ports SPI_LADC_0_io0_io]
 set_property PACKAGE_PIN B16 [get_ports SPI_LADC_0_io1_io]
 set_property PACKAGE_PIN B15 [get_ports SPI_LADC_0_ss_io]
 set_property PACKAGE_PIN AY11 [get_ports SPI_BASEDAC_0_sck_io]
 set_property PACKAGE_PIN AY10 [get_ports SPI_BASEDAC_0_io0_io]
 set_property PACKAGE_PIN AW9 [get_ports SPI_BASEDAC_0_io1_io]
 set_property PACKAGE_PIN AY9 [get_ports {SPI_BASEDAC_0_ss_io[0]}]

 set_property IOSTANDARD LVCMOS33 [get_ports SPI_LADC_0_ss_io]
 set_property IOSTANDARD LVCMOS33 [get_ports SPI_LADC_0_io0_io]
 set_property IOSTANDARD LVCMOS33 [get_ports SPI_LADC_0_io1_io]
 set_property IOSTANDARD LVCMOS33 [get_ports SPI_LADC_0_sck_io]
 set_property IOSTANDARD LVCMOS33 [get_ports {SPI_BASEDAC_0_ss_io[0]}]
 set_property IOSTANDARD LVCMOS33 [get_ports SPI_BASEDAC_0_io0_io]
 set_property IOSTANDARD LVCMOS33 [get_ports SPI_BASEDAC_0_io1_io]
 set_property IOSTANDARD LVCMOS33 [get_ports SPI_BASEDAC_0_sck_io]

 set_property DRIVE 4 [get_ports SPI_LADC_0_ss_io]
 set_property DRIVE 4 [get_ports SPI_LADC_0_io0_io]
 set_property DRIVE 4 [get_ports SPI_LADC_0_io1_io]
 set_property DRIVE 4 [get_ports SPI_LADC_0_sck_io]
 set_property DRIVE 4 [get_ports {SPI_BASEDAC_0_ss_io[0]}]
 set_property DRIVE 4 [get_ports SPI_BASEDAC_0_io0_io]
 set_property DRIVE 4 [get_ports SPI_BASEDAC_0_io1_io]
 set_property DRIVE 4 [get_ports SPI_BASEDAC_0_sck_io]

####################################################################################
# IIC pins
####################################################################################

 set_property PACKAGE_PIN N14 [get_ports IIC_CDCI6214_0_scl_io]
 set_property PACKAGE_PIN M14 [get_ports IIC_CDCI6214_0_sda_io]
 set_property PACKAGE_PIN H13 [get_ports IIC_SFP1_0_scl_io]
 set_property PACKAGE_PIN G13 [get_ports IIC_SFP1_0_sda_io]
 set_property PACKAGE_PIN L15 [get_ports IIC_SFP2_0_scl_io]
 set_property PACKAGE_PIN L14 [get_ports IIC_SFP2_0_sda_io]

 set_property IOSTANDARD LVCMOS33 [get_ports IIC_CDCI6214_0_scl_io]
 set_property IOSTANDARD LVCMOS33 [get_ports IIC_CDCI6214_0_sda_io]
 set_property IOSTANDARD LVCMOS33 [get_ports IIC_SFP1_0_scl_io]
 set_property IOSTANDARD LVCMOS33 [get_ports IIC_SFP1_0_sda_io]
 set_property IOSTANDARD LVCMOS33 [get_ports IIC_SFP2_0_sda_io]
 set_property IOSTANDARD LVCMOS33 [get_ports IIC_SFP2_0_scl_io]

 set_property DRIVE 4 [get_ports IIC_CDCI6214_0_scl_io]
 set_property DRIVE 4 [get_ports IIC_CDCI6214_0_sda_io]

####################################################################################
# Lgain ADC pins
####################################################################################

set_property PACKAGE_PIN G10 [get_ports {LADC_CTRL1_0[7]}]
set_property PACKAGE_PIN G12 [get_ports {LADC_CTRL1_0[6]}]
set_property PACKAGE_PIN F10 [get_ports {LADC_CTRL1_0[5]}]
set_property PACKAGE_PIN E11 [get_ports {LADC_CTRL1_0[4]}]
set_property PACKAGE_PIN C11 [get_ports {LADC_CTRL1_0[3]}]
set_property PACKAGE_PIN C10 [get_ports {LADC_CTRL1_0[2]}]
set_property PACKAGE_PIN A10 [get_ports {LADC_CTRL1_0[1]}]
set_property PACKAGE_PIN B11 [get_ports {LADC_CTRL1_0[0]}]
set_property PACKAGE_PIN H11 [get_ports {LADC_CTRL2_0[7]}]
set_property PACKAGE_PIN G11 [get_ports {LADC_CTRL2_0[6]}]
set_property PACKAGE_PIN E9 [get_ports {LADC_CTRL2_0[5]}]
set_property PACKAGE_PIN E10 [get_ports {LADC_CTRL2_0[4]}]
set_property PACKAGE_PIN D9 [get_ports {LADC_CTRL2_0[3]}]
set_property PACKAGE_PIN C9 [get_ports {LADC_CTRL2_0[2]}]
set_property PACKAGE_PIN A9 [get_ports {LADC_CTRL2_0[1]}]
set_property PACKAGE_PIN B10 [get_ports {LADC_CTRL2_0[0]}]
set_property PACKAGE_PIN A12 [get_ports {LADC_OPMODE_0}]
# set_property PACKAGE_PIN C13 [get_ports {LADC_SEN_0[7]}]
# set_property PACKAGE_PIN B16 [get_ports {LADC_SEN_0[6]}]
# set_property PACKAGE_PIN B15 [get_ports {LADC_SEN_0[5]}]
# set_property PACKAGE_PIN B13 [get_ports {LADC_SEN_0[4]}]
# set_property PACKAGE_PIN B12 [get_ports {LADC_SEN_0[3]}]
# set_property PACKAGE_PIN A15 [get_ports {LADC_SEN_0[2]}]
# set_property PACKAGE_PIN A14 [get_ports {LADC_SEN_0[1]}]
# set_property PACKAGE_PIN D11 [get_ports {LADC_SEN_0[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {LADC_CTRL1_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LADC_CTRL1_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LADC_CTRL1_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LADC_CTRL1_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LADC_CTRL1_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LADC_CTRL1_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LADC_CTRL1_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LADC_CTRL1_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LADC_CTRL2_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LADC_CTRL2_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LADC_CTRL2_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LADC_CTRL2_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LADC_CTRL2_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LADC_CTRL2_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LADC_CTRL2_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LADC_CTRL2_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LADC_OPMODE_0}]
# set_property IOSTANDARD LVCMOS33 [get_ports {LADC_SEN_0[7]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {LADC_SEN_0[6]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {LADC_SEN_0[5]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {LADC_SEN_0[4]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {LADC_SEN_0[3]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {LADC_SEN_0[2]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {LADC_SEN_0[1]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {LADC_SEN_0[0]}]

set_property PACKAGE_PIN A15 [get_ports {LDAC_SDATA_0[0]}]
set_property PACKAGE_PIN C15 [get_ports {LDAC_SDATA_0[1]}]
set_property PACKAGE_PIN A13 [get_ports {LDAC_SDATA_0[2]}]
set_property PACKAGE_PIN B12 [get_ports {LDAC_SDATA_0[3]}]
set_property PACKAGE_PIN D12 [get_ports {LDAC_SDATA_0[4]}]
set_property PACKAGE_PIN E15 [get_ports {LDAC_SDATA_0[5]}]
set_property PACKAGE_PIN E14 [get_ports {LDAC_SDATA_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LDAC_SDATA_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LDAC_SDATA_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LDAC_SDATA_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LDAC_SDATA_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LDAC_SDATA_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LDAC_SDATA_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LDAC_SDATA_0[6]}]

set_property PACKAGE_PIN C16 [get_ports {LDAC_SEN_0[0]}]
set_property PACKAGE_PIN A14 [get_ports {LDAC_SEN_0[1]}]
set_property PACKAGE_PIN D14 [get_ports {LDAC_SEN_0[2]}]
set_property PACKAGE_PIN C13 [get_ports {LDAC_SEN_0[3]}]
set_property PACKAGE_PIN D13 [get_ports {LDAC_SEN_0[4]}]
set_property PACKAGE_PIN D16 [get_ports {LDAC_SEN_0[5]}]
set_property PACKAGE_PIN E12 [get_ports {LDAC_SEN_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LDAC_SEN_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LDAC_SEN_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LDAC_SEN_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LDAC_SEN_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LDAC_SEN_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LDAC_SEN_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LDAC_SEN_0[6]}]

####################################################################################
# SFP pins
####################################################################################

set_property PACKAGE_PIN K16 [get_ports SFP2_MOD_ABS_0]
set_property PACKAGE_PIN J14 [get_ports SFP1_MOD_ABS_0]
set_property PACKAGE_PIN J16 [get_ports {SFP2_RS0_0}]
set_property PACKAGE_PIN J13 [get_ports {SFP1_RS0_0}]
set_property PACKAGE_PIN H16 [get_ports {SFP2_RS1_0}]
set_property PACKAGE_PIN H14 [get_ports {SFP1_RS1_0}]
set_property PACKAGE_PIN K17 [get_ports SFP2_RX_LOS_0]
set_property PACKAGE_PIN H15 [get_ports SFP1_RX_LOS_0]
set_property PACKAGE_PIN G16 [get_ports {SFP2_TX_DISABLE_0}]
set_property PACKAGE_PIN K14 [get_ports {SFP1_TX_DISABLE_0}]
set_property PACKAGE_PIN G15 [get_ports SFP2_TX_FAULT_0]
set_property PACKAGE_PIN K15 [get_ports SFP1_TX_FAULT_0]

set_property IOSTANDARD LVCMOS33 [get_ports SFP2_MOD_ABS_0]
set_property IOSTANDARD LVCMOS33 [get_ports SFP1_MOD_ABS_0]
set_property IOSTANDARD LVCMOS33 [get_ports {SFP2_RS0_0}]
set_property IOSTANDARD LVCMOS33 [get_ports {SFP1_RS0_0}]
set_property IOSTANDARD LVCMOS33 [get_ports {SFP2_RS1_0}]
set_property IOSTANDARD LVCMOS33 [get_ports {SFP1_RS1_0}]
set_property IOSTANDARD LVCMOS33 [get_ports SFP2_RX_LOS_0]
set_property IOSTANDARD LVCMOS33 [get_ports SFP1_RX_LOS_0]
set_property IOSTANDARD LVCMOS33 [get_ports {SFP2_TX_DISABLE_0}]
set_property IOSTANDARD LVCMOS33 [get_ports {SFP1_TX_DISABLE_0}]
set_property IOSTANDARD LVCMOS33 [get_ports SFP2_TX_FAULT_0]
set_property IOSTANDARD LVCMOS33 [get_ports SFP1_TX_FAULT_0]

####################################################################################
# GP I/O pins
####################################################################################

set_property PACKAGE_PIN F14 [get_ports {GPO_0[3]}]
set_property PACKAGE_PIN F13 [get_ports {GPO_0[2]}]
set_property PACKAGE_PIN F12 [get_ports {GPO_0[1]}]
set_property PACKAGE_PIN E16 [get_ports {GPO_0[0]}]
set_property PACKAGE_PIN K11 [get_ports {GPI_0[3]}]
set_property PACKAGE_PIN J11 [get_ports {GPI_0[2]}]
set_property PACKAGE_PIN K12 [get_ports {GPI_0[1]}]
set_property PACKAGE_PIN F9 [get_ports {GPI_0[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {GPO_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPO_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPO_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPO_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPI_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPI_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPI_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPI_0[0]}]

####################################################################################
# CDCI6214 pins
####################################################################################

set_property PACKAGE_PIN M15 [get_ports {CDCI6214_REF_SEL_0}]
set_property PACKAGE_PIN M17 [get_ports {CDCI6214_EEPROM_SEL_0}]
set_property PACKAGE_PIN N16 [get_ports {CDCI6214_OE_0}]
set_property PACKAGE_PIN M16 [get_ports CDCI6214_STATUS_0]
set_property PACKAGE_PIN N15 [get_ports {CDCI6214_OPMODE_0}]

set_property IOSTANDARD LVCMOS33 [get_ports {CDCI6214_REF_SEL_0}]
set_property IOSTANDARD LVCMOS33 [get_ports {CDCI6214_EEPROM_SEL_0}]
set_property IOSTANDARD LVCMOS33 [get_ports {CDCI6214_OE_0}]
set_property IOSTANDARD LVCMOS33 [get_ports CDCI6214_STATUS_0]
set_property IOSTANDARD LVCMOS33 [get_ports {CDCI6214_OPMODE_0}]


####################################################################################
# LEMO pins
####################################################################################

 set_property PACKAGE_PIN H9 [get_ports {LEMO[0]}]
 set_property PACKAGE_PIN H10 [get_ports {LEMO[1]}]

 set_property IOSTANDARD LVCMOS33 [get_ports {LEMO[1]}]
 set_property IOSTANDARD LVCMOS33 [get_ports {LEMO[0]}]

####################################################################################
# User IO pins
####################################################################################

set_property PACKAGE_PIN BA9 [get_ports PL_USER_CLK_LOCKED_LED]
set_property PACKAGE_PIN BB10 [get_ports PL_USER_CLK2_LED]
set_property PACKAGE_PIN BB11 [get_ports PS_PL_CLK_LED]
set_property PACKAGE_PIN BB9 [get_ports PL_USER_CLK_LED]

set_property IOSTANDARD LVCMOS33 [get_ports PL_USER_CLK_LOCKED_LED]
set_property IOSTANDARD LVCMOS33 [get_ports PL_USER_CLK2_LED]
set_property IOSTANDARD LVCMOS33 [get_ports PS_PL_CLK_LED]
set_property IOSTANDARD LVCMOS33 [get_ports PL_USER_CLK_LED]

# set_property PACKAGE_PIN AP11 [get_ports {DIPSW[7]}]
# set_property PACKAGE_PIN AP10 [get_ports {DIPSW[6]}]
# set_property PACKAGE_PIN AP12 [get_ports {DIPSW[5]}]
# set_property PACKAGE_PIN AR11 [get_ports {DIPSW[4]}]
# set_property PACKAGE_PIN AR10 [get_ports {DIPSW[3]}]
# set_property PACKAGE_PIN AT10 [get_ports {DIPSW[2]}]
# set_property PACKAGE_PIN AR12 [get_ports {DIPSW[1]}]
# set_property PACKAGE_PIN AT12 [get_ports {DIPSW[0]}]

#set_property IOSTANDARD LVCMOS33 [get_ports {DIPSW[7]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {DIPSW[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {DIPSW[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {DIPSW[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {DIPSW[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {DIPSW[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {DIPSW[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {DIPSW[0]}]

####################################################################################
# RJ45 pins
####################################################################################

# set_property PACKAGE_PIN AU11 [get_ports {RJ45_RST[0]}]
# set_property PACKAGE_PIN AV9 [get_ports {RJ45_RSV[0]}]
# set_property PACKAGE_PIN AV11 [get_ports {RJ45_TRG[0]}]

####################################################################################
# System Management Wizard pins
####################################################################################

#set_property PACKAGE_PIN AA19 [get_ports Vp_Vn_0_v_p]
#set_property IOSTANDARD ANALOG [get_ports Vp_Vn_0_v_p]

####################################################################################
# System reset pins
####################################################################################

set_property PACKAGE_PIN J23 [get_ports SYS_RST]
set_property IOSTANDARD LVCMOS12 [get_ports SYS_RST]

####################################################################################
# Lgain ADC
####################################################################################

create_clock -period 2.000 -name b64_clkin_p -waveform {0.000 1.000} [get_ports xiphy_rx_pins_1_pin26]
create_clock -period 2.000 -name b65_clkin_p -waveform {0.000 1.000} [get_ports xiphy_rx_pins_2_pin26]
create_clock -period 2.000 -name b66_clkin_p -waveform {0.000 1.000} [get_ports xiphy_rx_pins_3_pin26]
create_clock -period 2.000 -name b69_clkin_p -waveform {0.000 1.000} [get_ports xiphy_rx_pins_0_pin26]
set_false_path -through [get_nets {mogura2_fee_i/lgain_adc_blocks/rst}]

####################################################################################
# PL DDR4 pins
####################################################################################

# set_property LOC MMCM_X0Y3 [get_cells -hier -filter {NAME =~ */u_ddr4_infrastructure/gen_mmcme*.u_mmcme_adv_inst}]

# set_property PACKAGE_PIN K29 [get_ports ddr4_rtl_0_act_n]
# set_property PACKAGE_PIN M28 [get_ports {ddr4_rtl_0_adr[0]}]
# set_property PACKAGE_PIN L28 [get_ports {ddr4_rtl_0_adr[10]}]
# set_property PACKAGE_PIN J29 [get_ports {ddr4_rtl_0_adr[11]}]
# set_property PACKAGE_PIN J28 [get_ports {ddr4_rtl_0_adr[12]}]
# set_property PACKAGE_PIN R25 [get_ports {ddr4_rtl_0_adr[13]}]
# set_property PACKAGE_PIN G28 [get_ports {ddr4_rtl_0_adr[14]}]
# set_property PACKAGE_PIN K25 [get_ports {ddr4_rtl_0_adr[15]}]
# set_property PACKAGE_PIN L25 [get_ports {ddr4_rtl_0_adr[16]}]
# set_property PACKAGE_PIN G27 [get_ports {ddr4_rtl_0_adr[1]}]
# set_property PACKAGE_PIN M27 [get_ports {ddr4_rtl_0_adr[2]}]
# set_property PACKAGE_PIN K26 [get_ports {ddr4_rtl_0_adr[3]}]
# set_property PACKAGE_PIN L29 [get_ports {ddr4_rtl_0_adr[4]}]
# set_property PACKAGE_PIN R26 [get_ports {ddr4_rtl_0_adr[5]}]
# set_property PACKAGE_PIN E30 [get_ports {ddr4_rtl_0_adr[6]}]
# set_property PACKAGE_PIN R27 [get_ports {ddr4_rtl_0_adr[7]}]
# set_property PACKAGE_PIN F30 [get_ports {ddr4_rtl_0_adr[8]}]
# set_property PACKAGE_PIN P27 [get_ports {ddr4_rtl_0_adr[9]}]
# set_property PACKAGE_PIN H29 [get_ports {ddr4_rtl_0_ba[0]}]
# set_property PACKAGE_PIN N26 [get_ports {ddr4_rtl_0_ba[1]}]
# set_property PACKAGE_PIN H28 [get_ports {ddr4_rtl_0_bg[0]}]
# set_property PACKAGE_PIN K27 [get_ports {ddr4_rtl_0_bg[1]}]
# set_property PACKAGE_PIN N25 [get_ports {ddr4_rtl_0_ck_t[0]}]
# set_property PACKAGE_PIN M25 [get_ports {ddr4_rtl_0_ck_c[0]}]
# set_property PACKAGE_PIN J27 [get_ports {ddr4_rtl_0_cke[0]}]
# set_property PACKAGE_PIN M26 [get_ports {ddr4_rtl_0_cs_n[0]}]
# set_property PACKAGE_PIN R21 [get_ports {ddr4_rtl_0_dm_n[0]}]
# set_property PACKAGE_PIN C30 [get_ports {ddr4_rtl_0_dm_n[1]}]
# set_property PACKAGE_PIN L23 [get_ports {ddr4_rtl_0_dm_n[2]}]
# set_property PACKAGE_PIN H26 [get_ports {ddr4_rtl_0_dm_n[3]}]
# set_property PACKAGE_PIN R22 [get_ports {ddr4_rtl_0_dq[0]}]
# set_property PACKAGE_PIN B31 [get_ports {ddr4_rtl_0_dq[10]}]
# set_property PACKAGE_PIN A29 [get_ports {ddr4_rtl_0_dq[11]}]
# set_property PACKAGE_PIN B32 [get_ports {ddr4_rtl_0_dq[12]}]
# set_property PACKAGE_PIN B27 [get_ports {ddr4_rtl_0_dq[13]}]
# set_property PACKAGE_PIN A30 [get_ports {ddr4_rtl_0_dq[14]}]
# set_property PACKAGE_PIN B30 [get_ports {ddr4_rtl_0_dq[15]}]
# set_property PACKAGE_PIN H24 [get_ports {ddr4_rtl_0_dq[16]}]
# set_property PACKAGE_PIN J22 [get_ports {ddr4_rtl_0_dq[17]}]
# set_property PACKAGE_PIN H25 [get_ports {ddr4_rtl_0_dq[18]}]
# set_property PACKAGE_PIN K22 [get_ports {ddr4_rtl_0_dq[19]}]
# set_property PACKAGE_PIN P23 [get_ports {ddr4_rtl_0_dq[1]}]
# set_property PACKAGE_PIN J24 [get_ports {ddr4_rtl_0_dq[20]}]
# set_property PACKAGE_PIN K24 [get_ports {ddr4_rtl_0_dq[21]}]
# set_property PACKAGE_PIN G22 [get_ports {ddr4_rtl_0_dq[22]}]
# set_property PACKAGE_PIN F22 [get_ports {ddr4_rtl_0_dq[23]}]
# set_property PACKAGE_PIN F25 [get_ports {ddr4_rtl_0_dq[24]}]
# set_property PACKAGE_PIN F23 [get_ports {ddr4_rtl_0_dq[25]}]
# set_property PACKAGE_PIN C23 [get_ports {ddr4_rtl_0_dq[26]}]
# set_property PACKAGE_PIN D23 [get_ports {ddr4_rtl_0_dq[27]}]
# set_property PACKAGE_PIN E26 [get_ports {ddr4_rtl_0_dq[28]}]
# set_property PACKAGE_PIN G25 [get_ports {ddr4_rtl_0_dq[29]}]
# set_property PACKAGE_PIN N24 [get_ports {ddr4_rtl_0_dq[2]}]
# set_property PACKAGE_PIN D26 [get_ports {ddr4_rtl_0_dq[30]}]
# set_property PACKAGE_PIN F24 [get_ports {ddr4_rtl_0_dq[31]}]
# set_property PACKAGE_PIN M22 [get_ports {ddr4_rtl_0_dq[3]}]
# set_property PACKAGE_PIN N23 [get_ports {ddr4_rtl_0_dq[4]}]
# set_property PACKAGE_PIN N21 [get_ports {ddr4_rtl_0_dq[5]}]
# set_property PACKAGE_PIN M23 [get_ports {ddr4_rtl_0_dq[6]}]
# set_property PACKAGE_PIN M21 [get_ports {ddr4_rtl_0_dq[7]}]
# set_property PACKAGE_PIN A32 [get_ports {ddr4_rtl_0_dq[8]}]
# set_property PACKAGE_PIN A27 [get_ports {ddr4_rtl_0_dq[9]}]
# set_property PACKAGE_PIN R24 [get_ports {ddr4_rtl_0_dqs_t[0]}]
# set_property PACKAGE_PIN P24 [get_ports {ddr4_rtl_0_dqs_c[0]}]
# set_property PACKAGE_PIN B28 [get_ports {ddr4_rtl_0_dqs_t[1]}]
# set_property PACKAGE_PIN A28 [get_ports {ddr4_rtl_0_dqs_c[1]}]
# set_property PACKAGE_PIN H23 [get_ports {ddr4_rtl_0_dqs_t[2]}]
# set_property PACKAGE_PIN G23 [get_ports {ddr4_rtl_0_dqs_c[2]}]
# set_property PACKAGE_PIN E22 [get_ports {ddr4_rtl_0_dqs_t[3]}]
# set_property PACKAGE_PIN D22 [get_ports {ddr4_rtl_0_dqs_c[3]}]
# set_property PACKAGE_PIN J26 [get_ports {ddr4_rtl_0_odt[0]}]
# set_property PACKAGE_PIN F29 [get_ports ddr4_rtl_0_reset_n]
# set_property PACKAGE_PIN H30 [get_ports C0_SYS_CLK_0_clk_p]
# set_property PACKAGE_PIN G30 [get_ports C0_SYS_CLK_0_clk_n]

# set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddr4_rtl_0_dqs_c[0]}]
# set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddr4_rtl_0_dqs_c[1]}]
# set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddr4_rtl_0_dqs_c[2]}]
# set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddr4_rtl_0_dqs_c[3]}]
# set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddr4_rtl_0_dqs_t[0]}]
# set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddr4_rtl_0_dqs_t[1]}]
# set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddr4_rtl_0_dqs_t[2]}]
# set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddr4_rtl_0_dqs_t[3]}]
# set_property IOSTANDARD DIFF_SSTL12 [get_ports C0_SYS_CLK_0_clk_n]
# set_property IOSTANDARD DIFF_SSTL12 [get_ports C0_SYS_CLK_0_clk_p]
# set_property IOSTANDARD DIFF_SSTL12_DCI [get_ports {ddr4_rtl_0_ck_c[0]}]
# set_property IOSTANDARD DIFF_SSTL12_DCI [get_ports {ddr4_rtl_0_ck_t[0]}]
# set_property IOSTANDARD LVCMOS12 [get_ports ddr4_rtl_0_reset_n]
# set_property IOSTANDARD POD12_DCI [get_ports {ddr4_rtl_0_dm_n[0]}]
# set_property IOSTANDARD POD12_DCI [get_ports {ddr4_rtl_0_dm_n[1]}]
# set_property IOSTANDARD POD12_DCI [get_ports {ddr4_rtl_0_dm_n[2]}]
# set_property IOSTANDARD POD12_DCI [get_ports {ddr4_rtl_0_dm_n[3]}]
# set_property IOSTANDARD POD12_DCI [get_ports {ddr4_rtl_0_dq[0]}]
# set_property IOSTANDARD POD12_DCI [get_ports {ddr4_rtl_0_dq[10]}]
# set_property IOSTANDARD POD12_DCI [get_ports {ddr4_rtl_0_dq[11]}]
# set_property IOSTANDARD POD12_DCI [get_ports {ddr4_rtl_0_dq[12]}]
# set_property IOSTANDARD POD12_DCI [get_ports {ddr4_rtl_0_dq[13]}]
# set_property IOSTANDARD POD12_DCI [get_ports {ddr4_rtl_0_dq[14]}]
# set_property IOSTANDARD POD12_DCI [get_ports {ddr4_rtl_0_dq[15]}]
# set_property IOSTANDARD POD12_DCI [get_ports {ddr4_rtl_0_dq[16]}]
# set_property IOSTANDARD POD12_DCI [get_ports {ddr4_rtl_0_dq[17]}]
# set_property IOSTANDARD POD12_DCI [get_ports {ddr4_rtl_0_dq[18]}]
# set_property IOSTANDARD POD12_DCI [get_ports {ddr4_rtl_0_dq[19]}]
# set_property IOSTANDARD POD12_DCI [get_ports {ddr4_rtl_0_dq[1]}]
# set_property IOSTANDARD POD12_DCI [get_ports {ddr4_rtl_0_dq[20]}]
# set_property IOSTANDARD POD12_DCI [get_ports {ddr4_rtl_0_dq[21]}]
# set_property IOSTANDARD POD12_DCI [get_ports {ddr4_rtl_0_dq[22]}]
# set_property IOSTANDARD POD12_DCI [get_ports {ddr4_rtl_0_dq[23]}]
# set_property IOSTANDARD POD12_DCI [get_ports {ddr4_rtl_0_dq[24]}]
# set_property IOSTANDARD POD12_DCI [get_ports {ddr4_rtl_0_dq[25]}]
# set_property IOSTANDARD POD12_DCI [get_ports {ddr4_rtl_0_dq[26]}]
# set_property IOSTANDARD POD12_DCI [get_ports {ddr4_rtl_0_dq[27]}]
# set_property IOSTANDARD POD12_DCI [get_ports {ddr4_rtl_0_dq[28]}]
# set_property IOSTANDARD POD12_DCI [get_ports {ddr4_rtl_0_dq[29]}]
# set_property IOSTANDARD POD12_DCI [get_ports {ddr4_rtl_0_dq[2]}]
# set_property IOSTANDARD POD12_DCI [get_ports {ddr4_rtl_0_dq[30]}]
# set_property IOSTANDARD POD12_DCI [get_ports {ddr4_rtl_0_dq[31]}]
# set_property IOSTANDARD POD12_DCI [get_ports {ddr4_rtl_0_dq[3]}]
# set_property IOSTANDARD POD12_DCI [get_ports {ddr4_rtl_0_dq[4]}]
# set_property IOSTANDARD POD12_DCI [get_ports {ddr4_rtl_0_dq[5]}]
# set_property IOSTANDARD POD12_DCI [get_ports {ddr4_rtl_0_dq[6]}]
# set_property IOSTANDARD POD12_DCI [get_ports {ddr4_rtl_0_dq[7]}]
# set_property IOSTANDARD POD12_DCI [get_ports {ddr4_rtl_0_dq[8]}]
# set_property IOSTANDARD POD12_DCI [get_ports {ddr4_rtl_0_dq[9]}]
# set_property IOSTANDARD SSTL12_DCI [get_ports ddr4_rtl_0_act_n]
# set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_rtl_0_adr[0]}]
# set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_rtl_0_adr[10]}]
# set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_rtl_0_adr[11]}]
# set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_rtl_0_adr[12]}]
# set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_rtl_0_adr[13]}]
# set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_rtl_0_adr[14]}]
# set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_rtl_0_adr[15]}]
# set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_rtl_0_adr[16]}]
# set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_rtl_0_adr[1]}]
# set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_rtl_0_adr[2]}]
# set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_rtl_0_adr[3]}]
# set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_rtl_0_adr[4]}]
# set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_rtl_0_adr[5]}]
# set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_rtl_0_adr[6]}]
# set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_rtl_0_adr[7]}]
# set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_rtl_0_adr[8]}]
# set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_rtl_0_adr[9]}]
# set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_rtl_0_ba[0]}]
# set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_rtl_0_ba[1]}]
# set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_rtl_0_bg[0]}]
# set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_rtl_0_bg[1]}]
# set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_rtl_0_cke[0]}]
# set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_rtl_0_cs_n[0]}]
# set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_rtl_0_odt[0]}]
# set_property SLEW FAST [get_ports ddr4_rtl_0_act_n]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_adr[0]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_adr[10]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_adr[11]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_adr[12]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_adr[13]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_adr[14]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_adr[15]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_adr[16]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_adr[1]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_adr[2]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_adr[3]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_adr[4]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_adr[5]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_adr[6]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_adr[7]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_adr[8]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_adr[9]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_ba[0]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_ba[1]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_bg[0]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_bg[1]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_ck_c[0]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_ck_t[0]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_cke[0]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_cs_n[0]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_dm_n[0]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_dm_n[1]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_dm_n[2]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_dm_n[3]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_dq[0]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_dq[10]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_dq[11]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_dq[12]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_dq[13]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_dq[14]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_dq[15]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_dq[16]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_dq[17]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_dq[18]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_dq[19]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_dq[1]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_dq[20]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_dq[21]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_dq[22]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_dq[23]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_dq[24]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_dq[25]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_dq[26]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_dq[27]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_dq[28]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_dq[29]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_dq[2]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_dq[30]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_dq[31]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_dq[3]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_dq[4]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_dq[5]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_dq[6]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_dq[7]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_dq[8]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_dq[9]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_dqs_c[0]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_dqs_c[1]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_dqs_c[2]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_dqs_c[3]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_dqs_t[0]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_dqs_t[1]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_dqs_t[2]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_dqs_t[3]}]
# set_property SLEW FAST [get_ports {ddr4_rtl_0_odt[0]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports ddr4_rtl_0_act_n]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_adr[0]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_adr[10]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_adr[11]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_adr[12]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_adr[13]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_adr[14]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_adr[15]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_adr[16]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_adr[1]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_adr[2]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_adr[3]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_adr[4]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_adr[5]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_adr[6]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_adr[7]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_adr[8]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_adr[9]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_ba[0]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_ba[1]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_bg[0]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_bg[1]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_ck_c[0]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_ck_t[0]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_cke[0]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_cs_n[0]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_dm_n[0]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_dm_n[1]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_dm_n[2]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_dm_n[3]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_dq[0]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_dq[10]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_dq[11]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_dq[12]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_dq[13]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_dq[14]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_dq[15]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_dq[16]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_dq[17]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_dq[18]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_dq[19]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_dq[1]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_dq[20]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_dq[21]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_dq[22]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_dq[23]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_dq[24]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_dq[25]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_dq[26]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_dq[27]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_dq[28]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_dq[29]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_dq[2]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_dq[30]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_dq[31]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_dq[3]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_dq[4]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_dq[5]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_dq[6]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_dq[7]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_dq[8]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_dq[9]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_dqs_c[0]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_dqs_c[1]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_dqs_c[2]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_dqs_c[3]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_dqs_t[0]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_dqs_t[1]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_dqs_t[2]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_dqs_t[3]}]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_rtl_0_odt[0]}]
# set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_rtl_0_dm_n[0]}]
# set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_rtl_0_dm_n[1]}]
# set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_rtl_0_dm_n[2]}]
# set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_rtl_0_dm_n[3]}]
# set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_rtl_0_dq[0]}]
# set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_rtl_0_dq[10]}]
# set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_rtl_0_dq[11]}]
# set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_rtl_0_dq[12]}]
# set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_rtl_0_dq[13]}]
# set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_rtl_0_dq[14]}]
# set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_rtl_0_dq[15]}]
# set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_rtl_0_dq[16]}]
# set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_rtl_0_dq[17]}]
# set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_rtl_0_dq[18]}]
# set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_rtl_0_dq[19]}]
# set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_rtl_0_dq[1]}]
# set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_rtl_0_dq[20]}]
# set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_rtl_0_dq[21]}]
# set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_rtl_0_dq[22]}]
# set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_rtl_0_dq[23]}]
# set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_rtl_0_dq[24]}]
# set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_rtl_0_dq[25]}]
# set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_rtl_0_dq[26]}]
# set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_rtl_0_dq[27]}]
# set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_rtl_0_dq[28]}]
# set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_rtl_0_dq[29]}]
# set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_rtl_0_dq[2]}]
# set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_rtl_0_dq[30]}]
# set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_rtl_0_dq[31]}]
# set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_rtl_0_dq[3]}]
# set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_rtl_0_dq[4]}]
# set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_rtl_0_dq[5]}]
# set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_rtl_0_dq[6]}]
# set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_rtl_0_dq[7]}]
# set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_rtl_0_dq[8]}]
# set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_rtl_0_dq[9]}]
# set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_rtl_0_dqs_c[0]}]
# set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_rtl_0_dqs_c[1]}]
# set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_rtl_0_dqs_c[2]}]
# set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_rtl_0_dqs_c[3]}]
# set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_rtl_0_dqs_t[0]}]
# set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_rtl_0_dqs_t[1]}]
# set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_rtl_0_dqs_t[2]}]
# set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_rtl_0_dqs_t[3]}]


####################################################################################
# other options
####################################################################################

set_operating_conditions -heatsink custom
set_operating_conditions -thetasa 6.0
set_operating_conditions -airflow 0

#set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
#set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
#set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
#connect_debug_port dbg_hub/clk [get_nets clk]
